name: fetch-game-puzzles

permissions:
  contents: write

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: 'requirements.txt'

      - name: Run Python script
        run: python3 fetchpuzzles.py

      - name: Commit puzzle file and images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Colorku/src/data
          git add Puzzles/
          git diff --cached --quiet || git commit -m "Added puzzles for $(date +'%Y-%m-%d')"
          git push
